[package]
name = "bender_stroker"
version = "0.1.0"
authors = ["Eddy Bruel <ejpbruel@gmail.com>"]
edition = "2021"

[dependencies]
bender_filler = { path = "../filler" }
bender_geometry = { path = "../geometry" }
bender_offsetter = { path = "../offsetter" }