#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

workspace_toml="Cargo.toml"
example_toml="examples/native_text_input/Cargo.toml"
example_rs="examples/native_text_input/src/main.rs"
example_ui_test="examples/native_text_input/tests/ui.rs"
splash_file="makepad.splash"
studio_gate="tools/native_textinput_studio_gate.sh"
device_evidence="tools/native_textinput_device_runtime_evidence.sh"
composition_evidence="tools/native_textinput_macos_composition_evidence.sh"
leak_evidence="tools/native_textinput_macos_leak_smoke.sh"
static_evidence="tools/native_textinput_static_evidence.sh"
runtime_preflight="tools/native_textinput_runtime_preflight.sh"
completion_run_all="tools/native_textinput_completion_run_all.sh"
completion_audit="tools/native_textinput_completion_audit.sh"
poc_verify="tools/native_textinput_poc_verify.sh"
roadmap_doc="docs/native-textinput-macos-poc.roadmap.md"
evidence_readme="docs/native-textinput-evidence/README.md"
audit_doc="docs/native-textinput-macos-poc.audit.md"
widget_tree_rs="widgets/src/widget_tree.rs"

require_pattern() {
    local file="$1"
    local pattern="$2"
    local description="$3"
    if ! rg -q -- "$pattern" "$file"; then
        echo "missing ${description}: ${pattern} in ${file}" >&2
        exit 1
    fi
}

require_fixed_pattern() {
    local file="$1"
    local pattern="$2"
    local description="$3"
    if ! rg -Fq -- "$pattern" "$file"; then
        echo "missing ${description}: ${pattern} in ${file}" >&2
        exit 1
    fi
}

require_absent_pattern() {
    local file="$1"
    local pattern="$2"
    local description="$3"
    if rg -q -- "$pattern" "$file"; then
        echo "unexpected ${description}: ${pattern} in ${file}" >&2
        exit 1
    fi
}

require_executable() {
    local file="$1"
    local description="$2"
    if [[ ! -x "$file" ]]; then
        echo "missing executable bit for ${description}: ${file}" >&2
        exit 1
    fi
}

require_executable "$studio_gate" "Studio gate helper"
require_executable "$device_evidence" "device runtime evidence helper"
require_executable "$composition_evidence" "macOS composition evidence helper"
require_executable "$leak_evidence" "macOS leak evidence helper"
require_executable "$static_evidence" "static evidence helper"
require_executable "$runtime_preflight" "runtime preflight helper"
require_executable "$completion_run_all" "completion runner"
require_executable "$completion_audit" "completion audit helper"
require_executable "$poc_verify" "POC verifier"
require_executable "tools/native_textinput_macos_studio_smoke.sh" "macOS Studio smoke helper"

require_pattern "$workspace_toml" "\"examples/native_text_input\"" "workspace member"
require_pattern "$example_toml" "name = \"makepad-example-native-text-input\"" "example package name"
require_pattern "$example_toml" "makepad-widgets = \\{ path = \"../../widgets\"" "example widgets dependency"
require_pattern "$example_toml" "makepad-test = \\{ path = \"../../libs/makepad_test\"" "example UI test dependency"

require_pattern "$example_rs" "app_main!\\(App\\)" "example app entry"
require_pattern "$example_rs" "crate::makepad_widgets::script_mod\\(vm\\)" "widgets script registration"
require_pattern "$example_rs" "NativeTextInput\\{" "NativeTextInput usage"
require_pattern "$example_rs" "NativeLabel\\{" "NativeLabel usage"
require_pattern "$example_rs" "native_input := NativeTextInput" "named smoke input"
require_pattern "$example_rs" "secure_native_input := NativeTextInput" "named secure smoke input"
require_pattern "$example_rs" "let SmokeControl = View" "separated smoke control label and hit target"
require_pattern "$example_rs" "Primary field commands" "primary command group label"
require_pattern "$example_rs" 'NativeLabel\{width: Fill height: Fill text: "Select All"\}' "native command label overlay"
require_pattern "$example_rs" "status_label := NativeLabel" "visible native event-state panel"
require_pattern "$example_rs" "self\\.ui\\.native_label\\(cx, id\\)\\.set_text" "native event-state update path"
require_pattern "$example_rs" "focus_button := SmokeButton\\{\\}" "transparent focus hit target"
require_pattern "$example_rs" "secure: true" "secure smoke input property"
require_pattern "$example_rs" "width: 132" "stable smoke button width"
require_pattern "$example_rs" "focus_button := SmokeButton" "focus button"
require_pattern "$example_rs" "set_button := SmokeButton" "set text button"
require_pattern "$example_rs" "blur_button := SmokeButton" "blur button"
require_pattern "$example_rs" "select_button := SmokeButton" "select all button"
require_pattern "$example_rs" "copy_button := SmokeButton" "copy button"
require_pattern "$example_rs" "cut_button := SmokeButton" "cut button"
require_pattern "$example_rs" "paste_button := SmokeButton" "paste button"
require_pattern "$example_rs" "set_both_button := SmokeButton" "same-frame native update button"
require_pattern "$example_rs" "ScrollYView\\{" "clipped host scroll scenario"
require_pattern "$example_rs" "clipped_native_input := NativeTextInput" "clipped NativeTextInput scenario"
require_pattern "$example_rs" "same-frame native updates requested" "same-frame update status"
require_pattern "$example_rs" "input\\.changed\\(actions\\)" "changed action handling"
require_pattern "$example_rs" "input\\.key_focus\\(actions\\)" "focus action handling"
require_pattern "$example_rs" "input\\.key_focus_lost\\(actions\\)" "blur action handling"
require_pattern "$example_rs" "input\\.selection_changed\\(actions\\)" "selection action handling"

require_pattern "$example_ui_test" "native_text_input_smoke_controls_are_visible" "example UI smoke visibility test"
require_pattern "$example_ui_test" "native_text_input_buttons_update_status_labels" "example UI button status test"
require_pattern "$example_ui_test" "native_text_input_command_buttons_update_status_labels" "example UI native command status test"
require_pattern "$example_ui_test" "native_label_update_path_is_drivable" "example UI NativeLabel update test"
require_pattern "$example_ui_test" "native_text_input_same_frame_update_path_is_drivable" "example UI same-frame test"
require_pattern "$example_ui_test" "Selector::id\\(\"native_input\"\\)" "example UI native input selector"
require_pattern "$example_ui_test" "Selector::id\\(\"secure_native_input\"\\)" "example UI secure native input selector"
require_pattern "$example_ui_test" "Selector::id\\(\"native_label\"\\)" "example UI native label selector"
require_pattern "$example_ui_test" "Selector::id\\(\"clipped_native_input\"\\)" "example UI clipped input selector"
require_pattern "$example_ui_test" "Selector::id\\(\"label_button\"\\)" "example UI native label button selector"
require_pattern "$example_ui_test" "Selector::id\\(\"select_button\"\\)" "example UI select command selector"
require_pattern "$example_ui_test" "Selector::id\\(\"copy_button\"\\)" "example UI copy command selector"
require_pattern "$example_ui_test" "Selector::id\\(\"cut_button\"\\)" "example UI cut command selector"
require_pattern "$example_ui_test" "Selector::id\\(\"paste_button\"\\)" "example UI paste command selector"
require_pattern "$example_ui_test" "Selector::id\\(\"set_both_button\"\\)" "example UI same-frame selector"
require_pattern "$example_ui_test" "wait_value\\(\"hello native\"\\)" "example UI native input value state assertion"
require_pattern "$example_ui_test" "wait_value\\(\"same frame native input\"\\)" "example UI same-frame native input value assertion"
require_pattern "$example_ui_test" "NativeLabel updated through shared host registry" "example UI native label text assertion"
require_pattern "$example_ui_test" "NativeLabel updated in same frame" "example UI same-frame native label assertion"
require_pattern "$widget_tree_rs" "crate::native_text_input::NativeTextInput" "WidgetSnapshot NativeTextInput import"
require_pattern "$widget_tree_rs" "borrow::<NativeTextInput>" "WidgetSnapshot NativeTextInput value support"

require_pattern "$splash_file" "RunStudioRelease\\{name: \"makepad-example-native-text-input\"\\}" "Studio release RunItem"
require_pattern "$splash_file" "RunStudioNativeTextInputDiag\\{name: \"makepad-example-native-text-input-diag\"\\}" "Studio diagnostic RunItem"
require_pattern "$splash_file" "RunNativeTextInputStandalone\\{name: \"makepad-example-native-text-input-macos-standalone\"\\}" "macOS standalone RunItem"
require_pattern "$splash_file" "RunNativeTextInputStandaloneDiag\\{name: \"makepad-example-native-text-input-macos-standalone-diag\"\\}" "macOS standalone diagnostic RunItem"
require_pattern "$splash_file" "RunIosSimPackage\\{name: \"makepad-example-native-text-input-ios-sim\", package_name: \"makepad-example-native-text-input\"\\}" "iOS simulator RunItem"
require_pattern "$splash_file" "RunAndroidPackage\\{name: \"makepad-example-native-text-input-android\", package_name: \"makepad-example-native-text-input\"\\}" "Android RunItem"
require_pattern "$splash_file" "RunOhosPackage\\{name: \"makepad-example-native-text-input-ohos\", package_name: \"makepad-example-native-text-input\"\\}" "OpenHarmony RunItem"
require_pattern "$splash_file" "RunOhosPackage\\{name: \"makepad-example-aichat-ohos\", package_name: \"makepad-example-aichat\"\\}" "aichat OpenHarmony RunItem"
require_pattern "$splash_file" "--features\" \"diag-native-leak-count\"" "diagnostic feature flag"
require_pattern "$splash_file" "\"apple\" \"ios\" \"run-sim\" \"-p\" self\\.package_name \"--release\"" "iOS simulator release command"
require_pattern "$splash_file" "\"android\" \"--no-icon\" \"--small-fonts\" \"run\" \"-p\" self\\.package_name \"--release\"" "Android release command"
require_pattern "$splash_file" "\"ohos\" \"run\" \"-p\" self\\.package_name \"--release\"" "OpenHarmony release command"

require_pattern "$studio_gate" "target_name=\"makepad-example-native-text-input\"" "Studio gate default target"
require_pattern "$studio_gate" "target_name=\"makepad-example-native-text-input-diag\"" "Studio gate diagnostic target"
require_pattern "$studio_gate" "refusing to RunItem without --clear-build-id or --allow-no-clear" "Studio gate clear-build guard"
require_pattern "$studio_gate" "--self-test" "Studio gate self-test option"
require_pattern "$studio_gate" "NativeTextInput Studio gate self-test passed" "Studio gate self-test success message"
require_pattern "$studio_gate" "should_refuse_runitem" "Studio gate clear-build guard self-test"

require_pattern "$device_evidence" "makepad-example-native-text-input-ios-sim" "iOS evidence RunItem"
require_pattern "$device_evidence" "makepad-example-native-text-input-android" "Android evidence RunItem"
require_pattern "$device_evidence" "makepad-example-native-text-input-ohos" "OpenHarmony evidence RunItem"
require_pattern "$device_evidence" "missing required --device" "device evidence requires device"
require_pattern "$device_evidence" "--self-test" "device evidence self-test option"
require_pattern "$device_evidence" "run_self_test" "device evidence self-test implementation"
require_pattern "$device_evidence" "is_placeholder_device" "device evidence placeholder parser"
require_pattern "$device_evidence" "extract_build_id" "device evidence build id parser"
require_pattern "$device_evidence" "invalid --device placeholder" "device evidence rejects placeholder device"
require_pattern "$device_evidence" "UDID recorded" "device evidence rejects copied iOS README placeholder"
require_pattern "$device_evidence" "Android emulator or device" "device evidence rejects generic Android device"
require_pattern "$device_evidence" "serial or DevEco target name" "device evidence rejects copied OpenHarmony README placeholder"
require_pattern "$device_evidence" "127\\[.\\]0\\[.\\]0\\[.\\]1" "device evidence rejects OpenHarmony loopback simulator"
require_pattern "$device_evidence" "required_words=\\(keyboard changed selection clipboard\\)" "iOS required evidence words"
require_pattern "$device_evidence" "required_words=\\(IME changed selection clipboard\\)" "Android required evidence words"
require_pattern "$device_evidence" "required_words=\\(DevEco changed selection clipboard\\)" "OpenHarmony required evidence words"
require_pattern "$device_evidence" "wait_for_line.*AppStarted.*RunViewCreated" "device evidence app connection wait"
require_pattern "$device_evidence" "is_app_connection_line" "device evidence avoids duplicate app connection wait"
require_pattern "$device_evidence" 'Transcript: \$transcript' "device evidence transcript marker"

require_pattern "$composition_evidence" "required_words=\\(shared_host clipped scroll z_order mount_queue same_frame\\)" "macOS composition required evidence words"
require_pattern "$composition_evidence" 'query_widget "\$build_id" "clipped_native_input"' "macOS composition clipped widget query"
require_pattern "$composition_evidence" 'click_widget_center "\$build_id" "set_both_button"' "macOS composition same-frame click"
require_pattern "$composition_evidence" 'AfterScreenshot: \$screenshot_path' "macOS composition after screenshot marker"
require_pattern "$composition_evidence" 'Transcript: \$transcript' "macOS composition transcript marker"
require_pattern "$composition_evidence" "Screenshot response did not provide a readable file path" "macOS composition screenshot file guard"
require_pattern "$composition_evidence" 'BuildStarted.*AppStarted.*RunViewCreated' "macOS composition startup waits for build id"
require_pattern "$composition_evidence" 'AppStarted.*build_id.*RunViewCreated.*build_id' "macOS composition readiness waits for same build id"
require_pattern "$composition_evidence" "is_app_connection_line" "macOS composition avoids duplicate app connection wait"
require_pattern "$composition_evidence" "--self-test" "macOS composition self-test option"
require_pattern "$composition_evidence" "extract_screenshot_path" "macOS composition screenshot path parser"
require_pattern "$composition_evidence" "extract_widget_rect" "macOS composition widget rect parser"
require_pattern "$composition_evidence" "NativeTextInput macOS composition self-test passed" "macOS composition self-test success message"
require_pattern "tools/native_textinput_macos_studio_smoke.sh" 'Transcript: \$transcript' "macOS smoke transcript marker"
require_pattern "tools/native_textinput_macos_studio_smoke.sh" 'ClippedScreenshot: \$clipped_screenshot_path' "macOS smoke clipped screenshot marker"
require_pattern "tools/native_textinput_macos_studio_smoke.sh" "Clipped screenshot response did not provide a readable file path" "macOS smoke clipped screenshot file guard"
require_pattern "tools/native_textinput_macos_studio_smoke.sh" "Screenshot response did not provide a readable file path" "macOS smoke screenshot file guard"
require_pattern "tools/native_textinput_macos_studio_smoke.sh" 'BuildStarted.*AppStarted.*RunViewCreated' "macOS smoke startup waits for build id"
require_pattern "tools/native_textinput_macos_studio_smoke.sh" 'AppStarted.*build_id.*RunViewCreated.*build_id' "macOS smoke readiness waits for same build id"
require_pattern "tools/native_textinput_macos_studio_smoke.sh" "is_app_connection_line" "macOS smoke avoids duplicate app connection wait"
require_pattern "tools/native_textinput_macos_studio_smoke.sh" "SECONDS \\+ 8" "macOS smoke retries stale widget dumps"
require_pattern "tools/native_textinput_macos_studio_smoke.sh" "--self-test" "macOS smoke self-test option"
require_pattern "tools/native_textinput_macos_studio_smoke.sh" "extract_screenshot_path" "macOS smoke screenshot path parser"
require_pattern "tools/native_textinput_macos_studio_smoke.sh" "NativeTextInput macOS smoke self-test passed" "macOS smoke self-test success message"
require_pattern "$leak_evidence" 'Transcript: \$transcript' "macOS leak transcript marker"
require_pattern "$leak_evidence" 'BuildStarted.*AppStarted.*RunViewCreated' "macOS leak startup waits for build id"
require_pattern "$leak_evidence" 'AppStarted.*build_id.*RunViewCreated.*build_id' "macOS leak readiness waits for same build id"
require_pattern "$leak_evidence" "is_app_connection_line" "macOS leak avoids duplicate app connection wait"
require_pattern "$leak_evidence" "--self-test" "macOS leak self-test option"
require_pattern "$leak_evidence" "log_line_matches_live_count" "macOS leak live-count parser"
require_pattern "$leak_evidence" "NativeTextInput macOS leak self-test passed" "macOS leak self-test success message"
require_pattern "$leak_evidence" 'NativeTextInput live count: 3' "macOS leak counter matches example input count"
require_pattern "$leak_evidence" 'NativeTextInput live count: 0' "macOS leak counter returns to zero"

require_pattern "$static_evidence" "tools/native_textinput_poc_verify\\.sh" "static evidence verifier call"
require_pattern "$static_evidence" "NATIVE_TEXTINPUT_SKIP_STAGE_REPORT=1" "static evidence suppresses stale pre-write stage report"
require_pattern "$static_evidence" "tools/native_textinput_completion_audit\\.sh --stage-report" "static evidence prints final stage report after writing marker"
require_pattern "$static_evidence" "AndroidTarget:" "static evidence Android target marker"
require_pattern "$static_evidence" "OhosTarget:" "static evidence OpenHarmony target marker"
require_pattern "$static_evidence" "IosRelease:" "static evidence iOS release marker"
require_pattern "$static_evidence" "example_ui_test_compile" "static evidence example UI test marker"
require_pattern "$static_evidence" "runtime_preflight" "static evidence runtime preflight marker"
require_pattern "$static_evidence" "stage_report" "static evidence stage report marker"
require_pattern "$static_evidence" "--skip-ohos-target" "static evidence local OHOS skip option"
require_pattern "$static_evidence" "--self-test" "static evidence self-test option"
require_pattern "$static_evidence" "render_verify_command" "static evidence command renderer"
require_pattern "$static_evidence" "NativeTextInput static evidence self-test passed" "static evidence self-test success message"

require_pattern "$runtime_preflight" "ListBuilds" "runtime preflight ListBuilds check"
require_pattern "$runtime_preflight" "makepad-example-native-text-input" "runtime preflight normal RunItem check"
require_pattern "$runtime_preflight" "makepad-example-native-text-input-diag" "runtime preflight diagnostic RunItem check"
require_pattern "$runtime_preflight" "is missing or not executable" "runtime preflight helper executable checks"
require_pattern "$runtime_preflight" "--self-test" "runtime preflight self-test option"
require_pattern "$runtime_preflight" "NativeTextInput runtime preflight self-test passed" "runtime preflight self-test success message"
require_pattern "$runtime_preflight" "tools/native_textinput_studio_gate\\.sh --self-test" "runtime preflight covers Studio gate self-test"

require_pattern "$poc_verify" "cargo test -p makepad-example-native-text-input --test ui --no-run" "POC verifier example UI test compile gate"
require_pattern "$poc_verify" "tools/native_textinput_runtime_preflight\\.sh" "POC verifier runtime preflight syntax check"
require_pattern "$poc_verify" "tools/native_textinput_studio_gate\\.sh --self-test" "POC verifier Studio gate self-test"
require_pattern "$poc_verify" "tools/native_textinput_runtime_preflight\\.sh --self-test" "POC verifier runtime preflight self-test"
require_pattern "$poc_verify" "tools/native_textinput_completion_run_all\\.sh --self-test" "POC verifier completion runner self-test"
require_pattern "$poc_verify" "tools/native_textinput_macos_studio_smoke\\.sh --self-test" "POC verifier macOS smoke self-test"
require_pattern "$poc_verify" "tools/native_textinput_macos_composition_evidence\\.sh --self-test" "POC verifier macOS composition self-test"
require_pattern "$poc_verify" "tools/native_textinput_macos_leak_smoke\\.sh --self-test" "POC verifier macOS leak self-test"
require_pattern "$poc_verify" "tools/native_textinput_device_runtime_evidence\\.sh --self-test" "POC verifier device evidence self-test"
require_pattern "$poc_verify" "tools/native_textinput_static_evidence\\.sh --self-test" "POC verifier static evidence self-test"
require_pattern "$poc_verify" "tools/native_textinput_completion_audit\\.sh --self-test" "POC verifier completion audit self-test"
require_pattern "$poc_verify" "tools/native_textinput_completion_audit\\.sh --stage-report" "POC verifier completion audit stage report"
require_pattern "$completion_audit" "example_ui_test_compile" "completion audit example UI test marker"
require_pattern "$completion_audit" 'cargo test .*--test ui\|makepad_test' "completion audit rejects makepad_test runtime evidence"
require_pattern "$completion_audit" "tools/native_textinput_static_evidence\\.sh" "completion audit run-non-ui writes static evidence"
require_pattern "$completion_audit" "Compatibility alias retained for older runbooks" "completion audit blocked-target alias is explicit"
require_pattern "$completion_audit" "--skip-ohos-target" "completion audit local OHOS skip option"
require_pattern "$completion_audit" "--stage-report" "completion audit stage report option"
require_pattern "$completion_audit" "--allow-env-deferred" "completion audit env-deferred option"
require_pattern "$completion_audit" "NativeTextInput stage evidence report" "completion audit stage report output"
require_pattern "$completion_audit" "Environment-deferred verification checklist" "completion audit env-deferred checklist"
require_pattern "$completion_audit" "NativeTextInput environment-deferred audit passed" "completion audit env-deferred pass message"
require_pattern "$completion_audit" "P1\\.5.*clipped native host composition" "completion audit P1.5 stage report row"
require_pattern "$completion_audit" "P7.*native texture layer seed" "completion audit P7 stage report row"
require_pattern "$completion_audit" "require_marker_file" "completion audit marker file existence helper"
require_pattern "$completion_audit" "require_marker_file_pattern" "completion audit marker file content helper"
require_pattern "$completion_audit" "placeholder.*marker" "completion audit rejects placeholder marker paths"
require_pattern "$completion_audit" "readable non-empty file" "completion audit marker files are readable and non-empty"
require_pattern "$completion_audit" "macOS Studio screenshot file" "completion audit macOS smoke screenshot file check"
require_pattern "$completion_audit" "macOS Studio clipped screenshot file" "completion audit macOS smoke clipped screenshot file check"
require_pattern "$completion_audit" "macOS composition after screenshot file" "completion audit macOS composition after screenshot file check"
require_pattern "$completion_audit" "macOS Studio transcript file" "completion audit macOS smoke transcript file check"
require_pattern "$completion_audit" "macOS composition transcript file" "completion audit macOS composition transcript file check"
require_pattern "$completion_audit" "macOS leak transcript file" "completion audit macOS leak transcript file check"
require_pattern "$completion_audit" "iOS transcript file" "completion audit iOS transcript file check"
require_pattern "$completion_audit" "Android transcript file" "completion audit Android transcript file check"
require_pattern "$completion_audit" "OpenHarmony transcript file" "completion audit OpenHarmony transcript file check"
require_pattern "$completion_audit" "macOS Studio transcript content" "completion audit macOS smoke transcript content check"
require_pattern "$completion_audit" "runtime_preflight" "completion audit runtime preflight marker"
require_pattern "$completion_audit" "stage_report" "completion audit stage report static marker"
require_pattern "$completion_audit" "macOS leak transcript content" "completion audit macOS leak transcript content check"
require_pattern "$completion_audit" "macOS composition transcript screenshot content" "completion audit macOS composition transcript screenshot content check"
require_pattern "$completion_audit" "macOS composition transcript clipped input content" "completion audit macOS composition transcript clipped input content check"
require_pattern "$completion_audit" "macOS composition transcript same-frame button content" "completion audit macOS composition transcript same-frame button content check"
require_pattern "$completion_audit" "iOS transcript content" "completion audit iOS transcript content check"
require_pattern "$completion_audit" "Android transcript content" "completion audit Android transcript content check"
require_pattern "$completion_audit" "OpenHarmony transcript content" "completion audit OpenHarmony transcript content check"
require_pattern "$completion_audit" "--self-test" "completion audit self-test option"
require_pattern "$completion_audit" "run_self_test" "completion audit self-test implementation"
require_pattern "$completion_audit" "is_placeholder_device" "completion audit placeholder parser"
require_pattern "$completion_audit" "require_device_marker" "completion audit device marker helper"
require_pattern "$completion_audit" "iPhone Simulator" "completion audit rejects placeholder iOS device"
require_pattern "$completion_audit" "UDID recorded" "completion audit rejects copied iOS README placeholder"
require_pattern "$completion_audit" "Android emulator or device" "completion audit rejects placeholder Android device"
require_pattern "$completion_audit" "serial TBD" "completion audit rejects Android unknown serial placeholder"
require_pattern "$completion_audit" "OpenHarmony device" "completion audit rejects placeholder OpenHarmony device"
require_pattern "$completion_audit" "serial or DevEco target name" "completion audit rejects copied OpenHarmony README placeholder"
require_pattern "$completion_audit" "127\\[.\\]0\\[.\\]0\\[.\\]1" "completion audit rejects OpenHarmony loopback simulator"
require_pattern "$evidence_readme" "example_ui_test_compile" "evidence README example UI test marker"
require_pattern "$evidence_readme" "runtime_preflight" "evidence README runtime preflight marker"
require_pattern "$evidence_readme" "stage_report" "evidence README stage report marker"
require_pattern "$evidence_readme" "cargo test -p makepad-example-native-text-input --test ui --no-run" "evidence README example UI test command"
require_pattern "$evidence_readme" 'Runtime/device evidence files must not cite `cargo test ... --test ui` or' "evidence README rejects makepad_test runtime evidence"
require_pattern "$evidence_readme" 'Screenshot:` path must point to a' "evidence README screenshot file path rule"
require_pattern "$evidence_readme" "readable non-empty file" "evidence README screenshot file quality rule"
require_pattern "$evidence_readme" "audit rejects" "evidence README placeholder marker rejection"
require_pattern "$evidence_readme" 'Transcript:` must point to the saved' "evidence README transcript file path rule"
require_pattern "$evidence_readme" "non-empty Studio bridge response log" "evidence README transcript file quality rule"
require_pattern "$evidence_readme" "expected Studio responses" "evidence README transcript content rule"
require_pattern "$evidence_readme" 'AfterScreenshot:` is captured after' "evidence README composition after screenshot rule"
require_pattern "$evidence_readme" '`--run-non-ui` invokes `tools/native_textinput_static_evidence.sh` first' "evidence README run-non-ui static evidence behavior"
require_pattern "$evidence_readme" '`--run-non-ui --skip-ohos-target`' "evidence README local OHOS skip behavior"
require_pattern "$evidence_readme" '`--run-non-ui --skip-ios-release`' "evidence README local iOS release skip behavior"
require_pattern "$evidence_readme" 'final audit still fails while `OhosTarget` or `IosRelease` is' "evidence README local skip audit failure behavior"
require_pattern "$evidence_readme" "tools/native_textinput_runtime_preflight\\.sh" "evidence README runtime preflight command"
require_pattern "$evidence_readme" "native_textinput_completion_audit\\.sh --stage-report" "evidence README stage report command"
require_pattern "$evidence_readme" "native_textinput_completion_audit\\.sh --allow-env-deferred" "evidence README env-deferred audit command"
require_pattern "$evidence_readme" "native_textinput_completion_run_all\\.sh --dry-run" "evidence README completion dry-run command"
require_pattern "$evidence_readme" "UDID [0-9A-F-]+" "evidence README concrete iOS device example"
require_pattern "$evidence_readme" "Pixel 8 API 35 emulator \\(serial emulator-5554\\)" "evidence README concrete Android device example"
require_pattern "$evidence_readme" "OpenHarmony RK3568 DevEco target \\(serial OHOS-123456\\)" "evidence README concrete OpenHarmony device example"
require_pattern "$audit_doc" 'headless `cargo test ... --test ui` run cannot close runtime/device gates' "audit doc rejects makepad_test runtime evidence"
require_pattern "$audit_doc" "runtime_preflight" "audit doc runtime preflight marker"

require_pattern "$completion_run_all" "tools/native_textinput_static_evidence\\.sh" "completion runner static evidence step"
require_pattern "$completion_run_all" "tools/native_textinput_macos_studio_smoke\\.sh" "completion runner macOS smoke step"
require_pattern "$completion_run_all" "tools/native_textinput_macos_leak_smoke\\.sh" "completion runner macOS leak step"
require_pattern "$completion_run_all" "--dry-run" "completion runner dry-run option"
require_pattern "$completion_run_all" "NativeTextInput completion runbook" "completion runner dry-run runbook"
require_pattern "$completion_run_all" "Equivalent expanded sequence" "completion runner dry-run expanded sequence"
require_pattern "$completion_run_all" "macos-smoke-build-id" "completion runner dry-run build id chain"
require_pattern "$completion_run_all" "tools/native_textinput_macos_composition_evidence\\.sh" "completion runner composition step"
require_pattern "$completion_run_all" "read_build_id_from_evidence" "completion runner build id extraction"
require_pattern "$completion_run_all" "reject_placeholder_device" "completion runner rejects placeholder devices early"
require_pattern "$completion_run_all" "invalid --.*-device placeholder" "completion runner placeholder device error"
require_pattern "$completion_run_all" "--self-test" "completion runner self-test option"
require_pattern "$completion_run_all" "run_self_test" "completion runner self-test implementation"
require_pattern "$completion_run_all" "list_builds_has_native_textinput_build" "completion runner stale build parser function"
require_pattern "$completion_run_all" "check_no_existing_native_textinput_builds" "completion runner checks existing native builds"
require_pattern "$completion_run_all" "--list-builds --once" "completion runner uses ListBuilds preflight"
require_fixed_pattern "$completion_run_all" 'native_textinput_build_pattern=' "completion runner robust stale build package pattern"
require_pattern "$completion_run_all" "existing makepad-example-native-text-input build found" "completion runner rejects stale native builds"
require_pattern "$completion_run_all" '--clear-build-id "\$macos_smoke_build_id"' "completion runner clears old macOS smoke build"
require_pattern "$completion_run_all" 'macos_composition_build_id=' "completion runner reads composition build id"
require_pattern "$completion_run_all" '--clear-build-id "\$macos_composition_build_id"' "completion runner clears old macOS composition build"
require_pattern "$completion_run_all" 'macos_leak_build_id=' "completion runner reads macOS leak build id"
require_pattern "$completion_run_all" '--clear-build-id "\$macos_leak_build_id"' "completion runner clears old macOS leak build"
require_pattern "$completion_run_all" 'ios_build_id=' "completion runner reads iOS build id"
require_pattern "$completion_run_all" '--clear-build-id "\$ios_build_id"' "completion runner clears old iOS build"
require_pattern "$completion_run_all" 'android_build_id=' "completion runner reads Android build id"
require_pattern "$completion_run_all" '--clear-build-id "\$android_build_id"' "completion runner clears old Android build"
require_pattern "$completion_run_all" "platform ios" "completion runner iOS step"
require_pattern "$completion_run_all" "platform android" "completion runner Android step"
require_pattern "$completion_run_all" "platform ohos" "completion runner OpenHarmony step"
require_pattern "$completion_run_all" "tools/native_textinput_completion_audit\\.sh" "completion runner final audit step"
require_pattern "$completion_run_all" "performs its own" "completion runner usage explains internal ListBuilds check"
require_absent_pattern "$completion_run_all" "tools/native_textinput_studio_gate\\.sh --list-builds first" "stale manual ListBuilds instruction"

require_pattern "$roadmap_doc" "examples/native_text_input" "roadmap canonical native text input example"
require_pattern "$roadmap_doc" "examples/text_input" "roadmap TextInput reference example"
require_pattern "$roadmap_doc" "examples/todo" "roadmap app state reference example"
require_pattern "$roadmap_doc" "examples/uizoo/src/tab_textinput\\.rs" "roadmap widget matrix reference example"
require_pattern "$roadmap_doc" "examples/splash" "roadmap Studio runnable reference example"
require_pattern "$roadmap_doc" 'P0B 主 smoke 只验收非滚动容器里的 `native_input`' "roadmap P0B non-scroll smoke boundary"
require_pattern "$roadmap_doc" 'P1\.5 另用同一个 example 里的 `clipped_native_input`' "roadmap P1.5 clipped scroll boundary"
require_pattern "$roadmap_doc" "所有 macOS/iOS/Android/OHOS runtime evidence 都必须从这个 example 的 Studio RunItem 收集" "roadmap runtime evidence source"
require_pattern "$evidence_readme" 'generated `BuildId:` as the next helper' "evidence README completion runner build id handoff"
require_pattern "$evidence_readme" 'runtime sequence stays on known fresh Studio builds' "evidence README completion runner fresh build behavior"
require_pattern "$evidence_readme" 'The runner performs its own `ListBuilds` check' "evidence README completion runner ListBuilds check"
require_pattern "$evidence_readme" '--ios-device "iPhone 16 Simulator \(UDID [0-9A-F-]+\)"' "evidence README one-shot concrete iOS device"
require_pattern "$evidence_readme" '--android-device "Pixel 8 API 35 emulator \(serial emulator-5554\)"' "evidence README one-shot concrete Android device"
require_pattern "$evidence_readme" '--ohos-device "OpenHarmony RK3568 DevEco target \(serial OHOS-123456\)"' "evidence README one-shot concrete OpenHarmony device"
require_absent_pattern "$evidence_readme" '--ios-device "iPhone Simulator"' "generic iOS one-shot device"
require_absent_pattern "$evidence_readme" '--android-device "Android emulator or device"' "generic Android one-shot device"
require_absent_pattern "$evidence_readme" '--ohos-device "OpenHarmony device"' "generic OpenHarmony one-shot device"

static_line="$(rg -n "tools/native_textinput_static_evidence\\.sh" "$completion_run_all" | tail -n 1 | cut -d: -f1)"
audit_line="$(rg -n "tools/native_textinput_completion_audit\\.sh" "$completion_run_all" | tail -n 1 | cut -d: -f1)"
macos_line="$(rg -n "tools/native_textinput_macos_studio_smoke\\.sh" "$completion_run_all" | tail -n 1 | cut -d: -f1)"
if [[ -z "$static_line" || -z "$audit_line" || -z "$macos_line" ]]; then
    echo "missing completion runner ordering anchors" >&2
    exit 1
fi
if (( static_line <= macos_line || static_line >= audit_line )); then
    echo "completion runner must run static evidence after runtime helpers and before final audit" >&2
    exit 1
fi

echo "NativeTextInput example static contract check passed."
