#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

macos_input="platform/src/os/apple/apple_native_text_input.rs"
ios_input="platform/src/os/apple/apple_ios_native_text_input.rs"
macos_rs="platform/src/os/apple/macos/macos.rs"
ios_rs="platform/src/os/apple/ios/ios.rs"
widget_rs="widgets/src/native_text_input.rs"
cx_api_rs="platform/src/cx_api.rs"
splash_file="makepad.splash"
widgets_toml="widgets/Cargo.toml"

require_pattern() {
    local file="$1"
    local pattern="$2"
    local description="$3"
    if ! rg -q -- "$pattern" "$file"; then
        echo "missing ${description}: ${pattern} in ${file}" >&2
        exit 1
    fi
}

require_pattern "$widgets_toml" "diag-native-leak-count = \\[\"makepad-draw/diag-native-leak-count\"\\]" "widgets diagnostic feature"
require_pattern "$splash_file" "RunStudioNativeTextInputDiag\\{name: \"makepad-example-native-text-input-diag\"\\}" "diagnostic RunItem"
require_pattern "$splash_file" "--features\" \"makepad-widgets/diag-native-leak-count\"" "diagnostic feature flag"

require_pattern "$macos_input" "ClassDecl::new\\(\"MakepadNativeTextInputDelegate\"" "macOS delegate class"
require_pattern "$macos_input" "sel!\\(controlTextDidChange:\\)" "macOS changed selector"
require_pattern "$macos_input" "sel!\\(controlTextDidBeginEditing:\\)" "macOS focus selector"
require_pattern "$macos_input" "sel!\\(controlTextDidEndEditing:\\)" "macOS blur selector"
require_pattern "$macos_input" "sel!\\(textViewDidChangeSelection:\\)" "macOS selection selector"
require_pattern "$macos_input" "decl\\.add_ivar::<BOOL>\\(\"is_programmatic_update\"\\)" "macOS programmatic ivar"
require_pattern "$macos_input" "if is_programmatic != NO" "macOS programmatic guard"
require_pattern "$macos_input" "NativeTextInputChanged::new\\(text_input_id\\(this\\), text\\)" "macOS changed action"
require_pattern "$macos_input" "NativeTextInputFocusChanged::new\\(" "macOS focus action"
require_pattern "$macos_input" "NativeTextInputSelectionChanged::new\\(" "macOS selection action"
require_pattern "$macos_input" "selectedRange" "macOS selected range read"
require_pattern "$macos_input" "selection_start" "macOS selection state"
require_pattern "$macos_input" "clipped_native_host_layout\\(unclipped_rect, clipped_rect, visible\\)" "macOS clipped host layout"
require_pattern "$macos_input" "setMasksToBounds: YES" "macOS host clipping"
require_pattern "$macos_input" "setDelegate: self\\.delegate" "macOS delegate install"
require_pattern "$macos_input" "setStringValue: text" "macOS set text"
require_pattern "$macos_input" "setPlaceholderString: placeholder" "macOS placeholder"
require_pattern "$macos_input" "makeFirstResponder: self\\.field" "macOS focus command"
require_pattern "$macos_input" "makeFirstResponder: nil" "macOS blur command"
require_pattern "$macos_input" "selectText: nil" "macOS select all command"
require_pattern "$macos_input" "sel!\\(copy:\\)" "macOS copy command"
require_pattern "$macos_input" "sel!\\(cut:\\)" "macOS cut command"
require_pattern "$macos_input" "sel!\\(paste:\\)" "macOS paste command"
require_pattern "$macos_input" "performSelector: selector withObject: nil" "macOS edit command dispatch"
require_pattern "$macos_input" "setDelegate: nil" "macOS delegate cleanup"
require_pattern "$macos_input" "Retain count: alloc/init -> 1" "macOS retain-count cleanup comment"
require_pattern "$macos_input" "msg_send!\\[self\\.field, release\\]" "macOS field release"
require_pattern "$macos_input" "msg_send!\\[self\\.host_view, release\\]" "macOS host view release"
require_pattern "$macos_input" "msg_send!\\[self\\.delegate, release\\]" "macOS delegate release"
require_pattern "$macos_input" "NATIVE_TEXT_INPUT_LIVE_COUNT\\.fetch_add" "macOS leak counter increment"
require_pattern "$macos_input" "NATIVE_TEXT_INPUT_LIVE_COUNT\\.fetch_sub" "macOS leak counter decrement"
require_pattern "$macos_input" "impl Drop for MacosNativeTextInput" "macOS Drop cleanup"

require_pattern "$ios_input" "ClassDecl::new\\(\"MakepadIosNativeTextInputTarget\"" "iOS target class"
require_pattern "$ios_input" "sel!\\(editingChanged:\\)" "iOS changed selector"
require_pattern "$ios_input" "sel!\\(editingDidBegin:\\)" "iOS focus selector"
require_pattern "$ios_input" "sel!\\(editingDidEnd:\\)" "iOS blur selector"
require_pattern "$ios_input" "sel!\\(textFieldDidChangeSelection:\\)" "iOS selection selector"
require_pattern "$ios_input" "UI_CONTROL_EVENT_EDITING_CHANGED" "iOS editing changed event"
require_pattern "$ios_input" "decl\\.add_ivar::<BOOL>\\(\"is_programmatic_update\"\\)" "iOS programmatic ivar"
require_pattern "$ios_input" "if is_programmatic != NO" "iOS programmatic guard"
require_pattern "$ios_input" "NativeTextInputChanged::new\\(text_input_id\\(this\\), text\\)" "iOS changed action"
require_pattern "$ios_input" "NativeTextInputFocusChanged::new\\(" "iOS focus action"
require_pattern "$ios_input" "NativeTextInputSelectionChanged::new\\(" "iOS selection action"
require_pattern "$ios_input" "selectedTextRange" "iOS selected range read"
require_pattern "$ios_input" "offsetFromPosition: beginning toPosition" "iOS selection offset"
require_pattern "$ios_input" "setDelegate: self\\.target" "iOS delegate install"
require_pattern "$ios_input" "addTarget: self\\.target action: sel!\\(editingChanged:\\)" "iOS editing target install"
require_pattern "$ios_input" "setText: text" "iOS set text"
require_pattern "$ios_input" "setPlaceholder: placeholder" "iOS placeholder"
require_pattern "$ios_input" "becomeFirstResponder" "iOS focus command"
require_pattern "$ios_input" "resignFirstResponder" "iOS blur command"
require_pattern "$ios_input" "selectAll: nil" "iOS select all command"
require_pattern "$ios_input" "sel!\\(copy:\\)" "iOS copy command"
require_pattern "$ios_input" "sel!\\(cut:\\)" "iOS cut command"
require_pattern "$ios_input" "sel!\\(paste:\\)" "iOS paste command"
require_pattern "$ios_input" "performSelector: selector withObject: nil" "iOS edit command dispatch"
require_pattern "$ios_input" "removeTarget: self\\.target action: nil" "iOS target cleanup"
require_pattern "$ios_input" "msg_send!\\[self\\.field, release\\]" "iOS field release"
require_pattern "$ios_input" "msg_send!\\[self\\.target, release\\]" "iOS target release"
require_pattern "$ios_input" "impl Drop for IosNativeTextInput" "iOS Drop cleanup"

require_pattern "$macos_rs" "NativeHostProps::TextInput" "macOS TextInput create op"
require_pattern "$macos_rs" "NativeHostPropUpdate::TextInputText" "macOS text prop update"
require_pattern "$macos_rs" "NativeTextInputCommand::SelectAll => input\\.select_all\\(\\)" "macOS select all dispatch"
require_pattern "$macos_rs" "NativeTextInputCommand::Copy => input\\.copy\\(\\)" "macOS copy dispatch"
require_pattern "$macos_rs" "NativeTextInputCommand::Cut => input\\.cut\\(\\)" "macOS cut dispatch"
require_pattern "$macos_rs" "NativeTextInputCommand::Paste => input\\.paste\\(\\)" "macOS paste dispatch"

require_pattern "$ios_rs" "NativeHostProps::TextInput" "iOS TextInput create op"
require_pattern "$ios_rs" "NativeHostPropUpdate::TextInputText" "iOS text prop update"
require_pattern "$ios_rs" "NativeTextInputCommand::SelectAll => input\\.select_all\\(\\)" "iOS select all dispatch"
require_pattern "$ios_rs" "NativeTextInputCommand::Copy => input\\.copy\\(\\)" "iOS copy dispatch"
require_pattern "$ios_rs" "NativeTextInputCommand::Cut => input\\.cut\\(\\)" "iOS cut dispatch"
require_pattern "$ios_rs" "NativeTextInputCommand::Paste => input\\.paste\\(\\)" "iOS paste dispatch"

require_pattern "$widget_rs" "Cx::try_post_action\\(NativeTextInputCloseRequested::new" "widget Drop close request"
require_pattern "$widget_rs" "NativeTextInputAction::SelectionChanged" "widget selection action"
require_pattern "$cx_api_rs" "NativeTextInputCommand::SelectAll" "typed select all command"
require_pattern "$cx_api_rs" "NativeTextInputSelectionChanged" "typed selection event"

echo "Apple NativeTextInput static contract check passed."
