#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

cx_api_rs="platform/src/cx_api.rs"
cx_rs="platform/src/cx.rs"
action_rs="platform/src/action.rs"
lib_rs="platform/src/lib.rs"
native_host_rs="platform/src/os/apple/apple_native_host.rs"
native_label_rs="platform/src/os/apple/apple_native_label.rs"
widget_label_rs="widgets/src/native_label.rs"
widgets_lib_rs="widgets/src/lib.rs"
macos_rs="platform/src/os/apple/macos/macos.rs"
ios_rs="platform/src/os/apple/ios/ios.rs"
android_rs="platform/src/os/linux/android/android.rs"
ohos_rs="platform/src/os/linux/open_harmony/open_harmony.rs"

require_pattern() {
    local file="$1"
    local pattern="$2"
    local description="$3"
    if ! rg -q -- "$pattern" "$file"; then
        echo "missing ${description}: ${pattern} in ${file}" >&2
        exit 1
    fi
}

require_pattern "$cx_rs" "native_mount_queue: NativeMountQueue" "Cx native mount queue field"
require_pattern "$cx_api_rs" "pub enum NativeHostKind" "typed native host kind"
require_pattern "$cx_api_rs" "TextInput" "TextInput host kind"
require_pattern "$cx_api_rs" "Label" "Label host kind"
require_pattern "$cx_api_rs" "pub enum NativeHostProps" "typed native host props"
require_pattern "$cx_api_rs" "pub enum NativeHostPropUpdate" "typed native host prop updates"
require_pattern "$cx_api_rs" "pub enum NativeHostCommand" "typed native host command"
require_pattern "$cx_api_rs" "pub enum NativeTextInputCommand" "typed text input commands"
require_pattern "$cx_api_rs" "pub enum NativeMountMutation" "native mount mutation enum"
require_pattern "$cx_api_rs" "pub struct NativeMountQueue" "native mount queue"
require_pattern "$cx_api_rs" "fn coalesce\\(mutations: Vec<NativeMountMutation>\\)" "queue coalescing"
require_pattern "$cx_api_rs" "NativeMountMutation::Layout" "layout mutation"
require_pattern "$cx_api_rs" "NativeMountMutation::Props" "props mutation"
require_pattern "$cx_api_rs" "NativeMountMutation::Detach" "detach mutation"
require_pattern "$cx_api_rs" "NativeMountMutation::Close" "close mutation"
require_pattern "$cx_api_rs" "coalesced\\.retain\\(\\|existing: &NativeMountMutation\\| existing\\.id\\(\\) != \\*id\\)" "close drops prior same-host mutations"
require_pattern "$cx_api_rs" "for mutation in mutations\\.into_iter\\(\\)\\.rev\\(\\)" "reverse push for pop-order consumption"
require_pattern "$cx_api_rs" "pub\\(crate\\) fn flush_native_mount_queue\\(&mut self\\)" "Cx native queue flush"
require_pattern "$cx_api_rs" "self\\.native_mount_queue\\.flush_into\\(&mut self\\.platform_ops\\)" "queue flush into platform ops"
require_pattern "$cx_api_rs" "pub fn native_text_input\\(&mut self" "native text input Cx API"
require_pattern "$cx_api_rs" "pub fn native_label\\(&mut self" "native label Cx API"
require_pattern "$cx_api_rs" "NativeMountMutation::Create" "create mutation"
require_pattern "$cx_api_rs" "CxOsOp::CreateNativeView" "create native op"
require_pattern "$cx_api_rs" "CxOsOp::UpdateNativeViewLayout" "layout native op"
require_pattern "$cx_api_rs" "CxOsOp::UpdateNativeViewProps" "props native op"
require_pattern "$cx_api_rs" "CxOsOp::CommandNativeView" "command native op"
require_pattern "$cx_api_rs" "CxOsOp::DetachNativeView" "detach native op"
require_pattern "$cx_api_rs" "CxOsOp::CloseNativeView" "close native op"

require_pattern "$cx_api_rs" "fn native_mount_queue_flushes_in_pop_order\\(\\)" "queue order test"
require_pattern "$cx_api_rs" "fn native_mount_queue_coalesces_layout_and_props\\(\\)" "queue coalescing test"
require_pattern "$cx_api_rs" "fn native_mount_queue_create_and_close_in_one_flush_emit_nothing\\(\\)" "queue create+close elision test"
require_pattern "$cx_api_rs" "fn native_mount_queue_close_without_create_drops_prior_and_keeps_close\\(\\)" "queue close coalescing test"
require_pattern "$cx_api_rs" "fn native_mount_queue_preserves_commands\\(\\)" "queue command preservation test"
require_pattern "$cx_api_rs" "fn native_mount_queue_does_not_coalesce_props_across_commands\\(\\)" "queue props command barrier test"
require_pattern "$cx_api_rs" "fn native_mount_queue_does_not_coalesce_layout_across_commands\\(\\)" "queue layout command barrier test"
require_pattern "$cx_api_rs" "fn native_mount_queue_close_keeps_other_hosts\\(\\)" "queue close isolation test"
require_pattern "$cx_api_rs" "fn native_mount_queue_reentrant_flush_is_guarded\\(\\)" "queue reentrant guard test"
require_pattern "$cx_api_rs" "fn native_text_input_api_flushes_typed_mount_ops\\(\\)" "text input typed API test"
require_pattern "$cx_api_rs" "fn native_text_input_api_flushes_props_commands_and_detach\\(\\)" "text input props command detach test"
require_pattern "$cx_api_rs" "fn native_label_api_flushes_typed_mount_ops\\(\\)" "label typed API test"
require_pattern "$cx_api_rs" "fn native_label_api_close_coalesces_pending_mount_ops\\(\\)" "label close coalescing test"

require_pattern "$action_rs" "NativeTextInputCloseRequested" "text input close request action"
require_pattern "$action_rs" "NativeLabelCloseRequested" "label close request action"
require_pattern "$action_rs" "CxOsOp::CloseNativeView" "close action mapped to native op"
require_pattern "$lib_rs" "CxNativeLabel" "platform CxNativeLabel re-export"
require_pattern "$lib_rs" "NativeHostKind" "platform native host re-export"
require_pattern "$lib_rs" "NativeLabelCloseRequested" "platform label close re-export"

require_pattern "$widgets_lib_rs" "pub mod native_label;" "NativeLabel widget module"
require_pattern "$widgets_lib_rs" "crate::native_label::script_mod\\(vm\\)" "NativeLabel script registration"
require_pattern "$widget_label_rs" "mod.widgets.NativeLabelBase" "NativeLabel base registration"
require_pattern "$widget_label_rs" "pub struct NativeLabel" "NativeLabel widget struct"
require_pattern "$widget_label_rs" "cx\\.native_label\\(id\\)\\.spawn\\(text\\)" "NativeLabel spawn API"
require_pattern "$widget_label_rs" "cx\\.native_label\\(id\\)" "NativeLabel Cx API access"
require_pattern "$widget_label_rs" "\\.update\\(self\\.draw_bg\\.area\\(\\), self\\.visible\\)" "NativeLabel layout API"
require_pattern "$widget_label_rs" "cx\\.native_label\\(self\\.native_id\\(\\)\\)\\.detach\\(\\)" "NativeLabel detach API"
require_pattern "$widget_label_rs" "cx\\.native_label\\(self\\.native_id\\(\\)\\)\\.set_text\\(text\\)" "NativeLabel text prop API"
require_pattern "$widget_label_rs" "Cx::try_post_action\\(NativeLabelCloseRequested::new" "NativeLabel Drop close request"

require_pattern "$native_host_rs" "pub\\(crate\\) trait MacosNativeHost" "macOS native host trait"
require_pattern "$native_host_rs" "pub\\(crate\\) trait IosNativeHost" "iOS native host trait"
require_pattern "$native_host_rs" "pub\\(crate\\) fn clipped_native_host_layout" "clipped host layout helper"
require_pattern "$native_host_rs" "pub\\(crate\\) fn order_native_host_view" "native host z-order helper"
require_pattern "$native_host_rs" "addSubview: host_view positioned: NS_WINDOW_ABOVE relativeTo: nil" "native host z-order reinsert"
require_pattern "$native_host_rs" "fn offsets_content_inside_clipped_host\\(\\)" "clip offset test"
require_pattern "$native_host_rs" "fn hides_empty_clip\\(\\)" "empty clip test"
require_pattern "$native_label_rs" "pub\\(crate\\) struct MacosNativeLabel" "macOS native label"
require_pattern "$native_label_rs" "clipped_native_host_layout\\(unclipped_rect, clipped_rect, visible\\)" "NativeLabel clipped layout"
require_pattern "$native_label_rs" "order_native_host_view\\(parent_view, self\\.host_view\\)" "NativeLabel z-order update"
require_pattern "$native_label_rs" "setMasksToBounds: YES" "NativeLabel host clipping"
require_pattern "$native_label_rs" "impl MacosNativeHost for MacosNativeLabel" "NativeLabel host trait impl"
require_pattern "$native_label_rs" "msg_send!\\[self\\.field, release\\]" "NativeLabel field release"
require_pattern "$native_label_rs" "msg_send!\\[self\\.host_view, release\\]" "NativeLabel host view release"

require_pattern "$macos_rs" "native_hosts: HashMap<LiveId, Box<dyn MacosNativeHost>>" "macOS shared native host registry"
require_pattern "$macos_rs" "Box::new\\(MacosNativeTextInput::new" "macOS text input registry create"
require_pattern "$macos_rs" "Box::new\\(MacosNativeLabel::new" "macOS label registry create"
require_pattern "$macos_rs" "downcast_mut::<MacosNativeTextInput>" "macOS text input typed downcast"
require_pattern "$macos_rs" "downcast_mut::<MacosNativeLabel>" "macOS label typed downcast"
require_pattern "$macos_rs" "host\\.update_layout" "macOS generic host layout"
require_pattern "$macos_rs" "host\\.detach\\(\\)" "macOS generic host detach"
require_pattern "$macos_rs" "host\\.cleanup\\(\\)" "macOS generic host cleanup"
require_pattern "$macos_rs" "self\\.flush_native_mount_queue\\(\\)" "macOS native queue flush"
require_pattern "platform/src/os/apple/apple_native_text_input.rs" "order_native_host_view\\(parent_view, self\\.host_view\\)" "NativeTextInput z-order update"

require_pattern "$ios_rs" "native_hosts: HashMap<LiveId, Box<dyn IosNativeHost>>" "iOS shared native host registry"
require_pattern "$ios_rs" "Box::new\\(IosNativeTextInput::new" "iOS text input registry create"
require_pattern "$ios_rs" "host\\.update_layout" "iOS generic host layout"
require_pattern "$ios_rs" "host\\.detach\\(\\)" "iOS generic host detach"
require_pattern "$ios_rs" "host\\.cleanup\\(\\)" "iOS generic host cleanup"
require_pattern "$ios_rs" "self\\.flush_native_mount_queue\\(\\)" "iOS native queue flush"
require_pattern "$android_rs" "self\\.flush_native_mount_queue\\(\\)" "Android native queue flush"
require_pattern "$ohos_rs" "self\\.flush_native_mount_queue\\(\\)" "OpenHarmony native queue flush"

echo "NativeHost registry and mount queue static contract check passed."
